### ISSUE TITLE
Display profile for second hunter pet

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#212] opened 2018-08-28 21:31 UTC
Since patch 8.0, beastmaster hunters can take the "Animal Companion" talent allowing them to have 2 pets at a time. Since only one of them is controllable, only one of them has its profile displayed.

As per the point made in the last discussion on Discord, the second pet's owner is displayed in the tooltip, so it should be possible to get the information needed to support companion profiles on the second pet, unlike Hati.

**Comment by Ellypse** [comment] 2018-08-28 21:35
Duplicate of #52

**Closed by Ellypse** 2018-08-28 21:35 UTC
Labels: bug
