### ISSUE TITLE
Pet profile selection isn't fit with too many profiles 

### ISSUE THREAD

**Issue by Solanya** [Ellypse/Total-RP-3#167] opened 2018-07-21 16:29 UTC
If you have too many pet profiles, the dropdown can get out of bounds preventing from selecting a profile at the top or clicking on New Profile.

![](https://cdn.discordapp.com/attachments/373316460799459329/470258586308575272/abuse.png)

- If possible, scrolling could move the dropdown up or down ?

- Maybe going back to previous talks about categories in the profiles list, this would help alleviate the issue ? (It's still an issue if someone decides to make a huge number of categories, but much slower to get to...)

- Change the way to select a profile for a pet to use a browser ? (Less practical though)

**Comment by Ellypse** [comment] 2018-07-21 17:54
Duplicate of #54

**Closed by Ellypse** 2018-07-21 17:54 UTC
