### ISSUE TITLE
Disabling Class color in names

### ISSUE THREAD

**Issue by Hoparnoz** [Ellypse/Total-RP-3#203] opened 2018-08-13 16:28 UTC
**Is your feature request related to a problem? Please describe.**
Since version 1.4.4 all names are classcolored in chat, especially in emotes.

**Describe the solution you'd like**
An option for disabling classcolored names, customized or not.

**Comment by Solanya** [comment] 2018-08-13 16:28
Duplicate of https://github.com/Ellypse/Total-RP-3/issues/199

**Closed by Solanya** 2018-08-13 16:28 UTC
