### ISSUE TITLE
Custom names not showing

### ISSUE THREAD

**Issue by Svinjotaur** [Ellypse/Total-RP-3#236] opened 2018-11-04 03:53 UTC
I recently updated to the newest version of TRP and it worked fine, and after i downloaded some addons, and i jsut realised that the custom trp names arent showing anymore! I tried reloading addons, uninstaling all other addons, reloading Kui nameplates, deleting the WTF folder, uninstaling trp itself and all its plugins, uninstaling kui nameplates, the only thing i didnt reinstal yet is wow itself, i just dont know how to make custom TRP names apear again as nameplates....

**Comment by Solanya** [comment] 2018-11-04 11:50
There is a new version of the Total RP 3: KuiNameplates module (1.4.1) currently in beta to fix issues that came from changes to the main Kui Nameplates addon.

If you're using the Twitch App, you can right-click on the Total RP 3: KuiNameplates module and select Release Type > Beta to be able to download it. If you want to install it manually, here's the link : https://wow.curseforge.com/projects/total-rp-3-kuinameplates-module/files/2630744

**Comment by Ellypse** [comment] 2018-11-07 15:44
Closing, duplicate of https://github.com/Ellypse/Total-RP-3-KuiNameplates/issues/8

**Closed by Ellypse** 2018-11-07 15:44 UTC
