### ISSUE TITLE
TRP Not loading right -- Error with Realm Name Information?

### ISSUE THREAD

**Issue by Bunnybutts** [Ellypse/Total-RP-3#134] opened 2018-06-12 20:08 UTC
I am having an issue with my TRP where, whenever I launch a character, trp doesn't open and instead it gives me this error message:
Error During Addon Loading Sequence:
Sequence ID: Globals.addon: OnEnable
Sub-sequence ID: Globals.build
Error message: Interface/\AddOns\totalRP3\core\impl\globals.lua:129: Cannot have realm name information!
Is there anyway I could get some help fixing this?

**Comment by Ellypse** [comment] 2018-06-12 20:08
Duplicate of issue #133

**Closed by Ellypse** 2018-06-12 20:08 UTC
