### ISSUE TITLE
Love your update! But there is an issue.

### ISSUE THREAD

**Issue by ThundahV** [Ellypse/Total-RP-3#163] opened 2018-07-20 05:09 UTC
### What steps will reproduce the problem?
Not sure.
### What is the expected output? What do you see instead?
In the Additional information section, several of my things are missing, and instead, the second to first one has Value in the midst of it, and Field underneath, and then the last two pieces I have listed there.
### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes.
### What version of Total RP 3 are you using?
1.4.2
### Was it working in a previous version? If yes, which was the last good one?
Yes, 1.4.1
### Do you have an error log or screenshot of what happened?
Yes. https://imgur.com/a/8MUSELv
> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### If your issue is related to profile data, please provide your data file.
[totalRP3.lua.txt](https://github.com/Ellypse/Total-RP-3/files/2212517/totalRP3.lua.txt)

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment] 2018-07-20 06:32
Duplicate of #162

**Closed by Solanya** 2018-07-20 06:32 UTC
