### ISSUE TITLE
TRP profiles not in directory won't load. Also, map scan doesn't bring up any dots.

### ISSUE THREAD

**Issue by dwergaz** [Ellypse/Total-RP-3#137] opened 2018-06-13 02:56 UTC
### What steps will reproduce the problem?

Find someone who you know has a TRP profile and target them, then wait. It'll look like they have no RP addon. People whose TRP profile is already in my directory show up just fine, as do MRP and XRP profiles regardless of whether they're already in there.

### What is the expected output? What do you see instead?

I expect to see a new TRP profile load in, but I don't see anything, as if they have no TRP.

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?

Yep! That's how I usually play anyway.

### What version of Total RP 3 are you using?

The latest one, 1.3.5. This issue only began after I updated to it today.

### Was it working in a previous version? If yes, which was the last good one?

Yes. It was working on the version right before this one. 1.3.4.4, I think?

### Do you have an error log or screenshot of what happened?

No, but screenshots wouldn't help much here. It'd just be a person's name readout as if they have no TRP. 

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### Please provide any additional information below.

I went back and redownloaded 1.3.4.4, and the people whose TRPs wouldn't load now load in just fine. This is definitely caused by some change in 1.3.5.

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment] 2018-06-13 07:20
Duplicate of #136

**Closed by Solanya** 2018-06-13 07:20 UTC
