### ISSUE TITLE
Terrible Ethics, Even Worse Code

### ISSUE THREAD

**Issue by DDCorkum** [Ellypse/Total-RP-3#204] opened 2018-08-13 21:35 UTC
**Describe the bug**
Ellyb.lua lines 17 through 39 are, ironically, FORCING bug detection addons to report minor things like Deferred XML warnings.  The purpose of this code is evidently to stop people from blaming Ellyb for causing errors, but it has the fantastic effect of making it look like all the warning are an error caused by TotalRP 3 (which it is, really, at line 37).

The best part is that whomever wrote this has absolutely zero ethics, as made very clear in lines 23 through 26 where the functionality of other addons are purposefully screwed around with.   Even better that lines 21 and 22 even have an apology written in advance "Sorry... to those it will piss off."

If you, or your lib authors, knew they had to apologize in their source code to everyone else trying to troubleshoot problems... don't you think it would've been the clearest indicator you are doing something wrong?

So your code is terrible... and funnily enough making it look like you are at fault.   But your ethics are even worse.  If you did the right thing at the start, you wouldn't be blamed for causing errors in line 37 today.   Karma, I guess.

**Comment by Ellypse** [comment] 2018-08-13 21:36
I know.

**Comment by Ellypse** [comment] 2018-08-13 21:36
Duplicate of #200

**Closed by Ellypse** 2018-08-13 21:36 UTC
