### ISSUE TITLE
ElvUI chat not playing well with TRP3 chat

### ISSUE THREAD

**Issue by OraibiMoonGuard** [Ellypse/Total-RP-3#169] opened 2018-07-22 12:28 UTC
### What steps will reproduce the problem?

Loaded with just ElvUI (10.77) and TRP3 (1.4.3). Confirmed I have a last name in TRP3. ElvUI chat handling is turned on, but no particular ElvUI chat options enabled.

### What is the expected output? What do you see instead?

Typed (( test )), expected to see "[ (icon) Oraibi the Barrister]: says (( test ))", only saw "[Oraibi] says: (( test ))".

Turned off ElvUI chat functions, saw expected output as per normal from TRP3.

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?

Well, no. I turned off everything except ElvUI and TRP3, though. (Even rptags!)

### What version of Total RP 3 are you using?

1.4.3

### Was it working in a previous version? If yes, which was the last good one?

Yes, pre-8.01 I used ElvUI and saw TRP3 names.

### Do you have an error log or screenshot of what happened?
![elvui-trp3-chat-bug-02](https://user-images.githubusercontent.com/39206073/43045568-c9b646de-8d6f-11e8-8355-af6785cc96cc.png)
![elvui-trp3-chat-bug-03](https://user-images.githubusercontent.com/39206073/43045572-d101dbba-8d6f-11e8-9cfc-89cd9ab1cb69.png)
![elvui-trp3-chat-bug-05](https://user-images.githubusercontent.com/39206073/43045573-d65fb76c-8d6f-11e8-979c-e17a33552b1b.png)
![elvui-trp3-chat-bug-06](https://user-images.githubusercontent.com/39206073/43045575-dc923b6e-8d6f-11e8-967f-084de985fe45.png)
![elvui-trp3-chat-bug-07](https://user-images.githubusercontent.com/39206073/43045577-e4cec77a-8d6f-11e8-97f0-265f3cb51d63.png)

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### Please provide any additional information below.

ElvUI was updated lately too so this could very well be one of their problems, too!

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Ellypse** [comment] 2018-07-22 12:30
Duplicate of #135
This is an issue with ElvUI that should be fixed on their side.

**Comment by Solanya** [comment] 2018-07-22 12:33
"If this issue is not solved by this update, then a different ticket should be opened."
It's not a duplicate, name customization was fixed with the ElvUI compatibility module previously and working until 8.0.

**Comment by Ellypse** [comment] 2018-08-09 19:40
User error, module was disabled.

**Closed** 2018-08-09 19:39 UTC
