### ISSUE TITLE
Error on only one profile

### ISSUE THREAD

**Issue by WyldAynjel** [Ellypse/Total-RP-3#104] opened 2018-03-07 16:20 UTC
### What steps will reproduce the problem?
Every other character profile works except my worgen mage. Clicking on the 'About' section produces an error

### What is the expected output? What do you see instead?
No text in the 'About' section. Error. 

### Did you try having Total RP 3 as the only enabled addon and everything else (especially something like ElvUI) disabled?
Yes

### What version of Total RP 3 are you using?
Newest

### Was it working in a previous version? If yes, which was the last good one?
Yes, works on everything else.. just not the mage

### Do you have an error log or screenshot of what happened?

Message: Interface\AddOns\totalRP3\core\impl\utils.lua:848: bad argument #1 to 'abs' (number expected, got string)
Time: 03/07/18 11:16:15
Count: 2
Stack: Interface\AddOns\totalRP3\core\impl\utils.lua:848: bad argument #1 to 'abs' (number expected, got string)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
[C]: in function `abs'
Interface\AddOns\totalRP3\core\impl\utils.lua:848: in function <Interface\AddOns\totalRP3\core\impl\utils.lua:845>
[C]: in function `gsub'
Interface\AddOns\totalRP3\core\impl\utils.lua:845: in function `toHTML'
...alRP3\modules\register\characters\register_about.lua:121: in function `?'
...alRP3\modules\register\characters\register_about.lua:646: in function <...alRP3\modules\register\characters\register_about.lua:612>
...alRP3\modules\register\characters\register_about.lua:754: in function <...alRP3\modules\register\characters\register_about.lua:737>
...alRP3\modules\register\characters\register_about.lua:762: in function <...alRP3\modules\register\characters\register_about.lua:758>
...talRP3\modules\register\characters\register_main.lua:476: in function <...talRP3\modules\register\characters\register_main.lua:468>
Interface\AddOns\totalRP3\core\impl\ui_tools.lua:709: in function <Interface\AddOns\totalRP3\core\impl\ui_tools.lua:706>
Interface\AddOns\totalRP3\core\impl\ui_tools.lua:716: in function `callback'
...talRP3\modules\register\characters\register_main.lua:490: in function <...talRP3\modules\register\characters\register_main.lua:483>
Interface\AddOns\totalRP3\core\impl\ui_tools.lua:716: in function <Interface\AddOns\totalRP3\core\impl\ui_tools.lua:712>

Locals: errorMessage = "Interface\AddOns\totalRP3\core\impl\utils.lua:848: bad argument #1 to 'abs' (number expected, got string)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0

> If you don't see any errors, make sure that error reporting is enabled (`/console scriptErrors 1`) or install the [BugSack](https://mods.curse.com/addons/wow/BugSack) add-on.

### If your issue is related to profile data, please provide your data file.

> It is the `totalRP3.lua` file (not the .lua.bak files!) located in your `World of Warcraft/WTF/Account/ACCOUNT_NAME/SavedVariables` folder (replace `ACCOUNT_NAME` with your actual account name, visible on the Battle.net launcher, usually WoW1 for accounts created after the introduction of Battle.net). You can just drag and drop it here, no need for a third party service.

**Comment by Solanya** [comment] 2018-03-07 16:24
Total RP 3 version 1.3.2-beta2 solves this issue, you can download it here : https://wow.curseforge.com/projects/total-rp-3/files/2538165 or if you use the Twitch client, right-click on the addon in the list and switch Release type to Beta.
(One of the image tags in your worgen profile must not have numbers as the last two elements, which is triggering the error since a fix from 1.3.1.)

**Comment by Ellypse** [comment] 2018-03-07 16:26
Duplicate of issue #97

**Comment by WyldAynjel** [comment] 2018-03-07 16:26
Yup... for reference, it was the full moon picture. Removed it and no more error.

**Closed** 2018-03-08 10:04 UTC
Labels: duplicate
